[versions]
minestom = "2026.01.08-1.21.11"
fastutil = "8.5.12"

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
